### ISSUE TITLE
{Feature Request] Codelist values activity count

### ISSUE THREAD

**Issue by stevieflow** [codeforIATI/analytics#21]
**Is your feature request related to a problem? Please describe.**

For any particular publisher, it is very useful to see the range of codelist values that are being used (esp as this is being fixed: https://github.com/codeforIATI/IATI-Dashboard/issues/15 !)

An extra step would be to list the count of activities that use any value - to help understand how widespread (or not) this value is within any publisher (it could also be useful to aggregate these up at eg https://analytics.codeforiati.org/codelist/2/activity-date_@type.html)

**Describe the solution you'd like**

For a publisher  eg https://analytics.codeforiati.org/publisher/unhcr.html#p_codelists - first of all investigate whether we have these numbers stored?

**Describe alternatives you've considered**

Download a spreadsheet of the codelist values and counts?

**Additional context**

Given that several codelist values can be used for any codelist, by any publisher, exactly how we show this (in a table) would probably mean a new section to the publisher page -- as the existing codelist table provides a particular thing already.

Another way to investigate this would be to build up the pages for each codelist - eg: https://analytics.codeforiati.org/codelist/2/activity-date_@type.html - but add a filtered view for the publisher ~~ https://analytics.codeforiati.org/codelist/2/activity-date_@type.html?publisher=unhcr -- but that seems like a whole bunch of new functionality (on static pages...)

An alternative to this is to format the codelist pages similarly to element pages - https://analytics.codeforiati.org/element/iati-activity_activity-date_@type.html - which includes activity counts.  Hence, we'd provide on this page acivity counts for each codelist value, by publisher (which could be arranged two different ways...)

**Comment by andylolz** [comment]
> For a publisher eg https://analytics.codeforiati.org/publisher/unhcr.html#p_codelists - first of all investigate whether we have these numbers stored?

Yes, we definitely do. Here are the counts for UNHCR:
http://stats.codeforiati.org/current/aggregated-publisher/unhcr/codelist_values_by_major_version.json

How about adding the numbers on the popup, e.g.:
![Screenshot 2021-05-17 at 23 58 00](https://user-images.githubusercontent.com/464193/118566413-ba4e2800-b76b-11eb-9bdb-02f543f64168.png)

**Comment by stevieflow** [comment]
Thanks @andylolz 

> How about adding the totals on the popup

Yes, let's see how that works

**Comment by andylolz** [comment]
Nice okay – this should appear on https://analytics-dev.codeforiati.org/ shortly.

I’ve also added these counts to codelist element pages, e.g.:
![Screenshot 2021-05-18 at 10 05 24](https://user-images.githubusercontent.com/464193/118623955-a41e8700-b7c0-11eb-8f0c-3e610edfe791.png)

**Comment by andylolz** [comment]
Cool – this is live now e.g. here:
https://analytics.codeforiati.org/publisher/unops.html#p_codelists

and here:
https://analytics.codeforiati.org/codelist/2/activity-date_@type.html

**Comment by stevieflow** [comment]
Amazing, thanks

[more function request KLAXON]

It'd be useful to enable a CSV download of these values/pages....
