### ISSUE TITLE
[blank] values in attributes

### ISSUE THREAD

**Issue by stevieflow** [codeforIATI/analytics#45]
There are a number of instances where the attribute is published, but not populated.  For example:

https://aidstream.s3.us-west-2.amazonaws.com/xml/acet-activities.xml has a blank linked-data-uri attribute:

`<iati-activity last-updated-datetime="2019-06-18T10:43:52+00:00" xml:lang="en" default-currency="USD" humanitarian="false" hierarchy="1" linked-data-uri="">`

Analytics falsely counts these in the codelist breakdown - suggesting a value is provided ("Publishing this element"):

https://analytics.codeforiati.org/element/iati-activity_@linked-data-uri.html

I'm not sure of the best solution - but this covers all attributes, regardless of whether they should be populated by a codelist, boolean or string etc.

**Comment by andylolz** [comment]
Good point.

I’m tempted to reclassify an empty string as not publishing this element…

**Comment by andylolz** [comment]
I’ve had a go at a fix here: https://github.com/codeforIATI/IATI-Stats/pull/13

**Comment by stevieflow** [comment]
> I’m tempted to reclassify an empty string as “not publishing this element”

Yes, seems sensible to me

**Comment by andylolz** [comment]
This should be fixed now.

**Comment by stevieflow** [comment]
Should we put some disclaimer text to say that [BLANK] values are classed as not publishing?

**Comment by andylolz** [comment]
Oh, v good point

**Comment by andylolz** [comment]
Okay, I’ve added that now. It will appear on the next build.
