### ISSUE TITLE
Display links to individual licenses in a new column

### ISSUE THREAD

**Issue by notshi** [codeforIATI/analytics#52]
**Is your feature request related to a problem? Please describe.**
It's great to see the [number of files and publishers with licenses](https://analytics.codeforiati.org/licenses.html) in the data.

It would be really nice to have a link to these license pages so that we know what they are.

**Describe the solution you'd like**
There is metadata from the Registry that lets you know where this is via `license_url`. 
This url could be added as another column like 'License Id'.

For example
```json
"license_id": "cc-by",
"license_title": "Creative Commons Attribution",
"license_url": "http://www.opendefinition.org/licenses/cc-by",
```

**Comment by andylolz** [comment]
Nice, yes – this sounds great
