### ISSUE TITLE
Having trouble building

### ISSUE THREAD

**Issue by notshi** [codeforIATI/analytics#53]
**Describe the bug**

Thank you for the very helpful readme instructions.
I'm able to run both the `get_stats.sh` and `fetch_data.sh` scripts.
However, I'm currently stuck at `python plots.py` with this error message, presumably due to [this line](https://github.com/codeforIATI/analytics/blob/main/data.py#L195).

```
File "/home/git/analytics/data.py", line 195, in <module>
    metadata = json.load(open('./stats-calculated/metadata.json'), object_pairs_hook=OrderedDict)
FileNotFoundError: [Errno 2] No such file or directory: './stats-calculated/metadata.json'
```

I may be doing something wrong so any help is much appreciated.

**Screenshots**

![Screenshot-20210713174743-326x229](https://user-images.githubusercontent.com/1515961/125492926-db757c5f-b92a-4ae2-b3cc-4f0cab63b5e7.png)

These are currently all the files generated by the `get_stats.sh` script and `metadata.json` is not one of them.

**Comment by andylolz** [comment]
Very possible the README is not up to date. The best reference is the github action build script. Specifically, this bit:
https://github.com/codeforIATI/analytics/blob/1f40dc92d0f6beecd13ee72d237488becd0c1cbf/.github/workflows/build.yml#L25-L42

**Comment by andylolz** [comment]
Ah, okay yeah I think the problem was the README was out of date. I’ve fixed the get_stats script so it now does The Right Thing (though it probably takes a long time to run).

**Comment by notshi** [comment]
Thank you! Will confirm that this has fixed the issue and building is successful.

There was a rather worrying pause at `Publisher not matched: btc-ctb` in the last stage of `python make_html.py` but shell spat out the MissingURLGeneratorWarning after about half an hour or so and I was able to run the live development server.

**Comment by andylolz** [comment]
> There was a rather worrying pause at `Publisher not matched: btc-ctb` in the last stage of `python make_html.py` but shell spat out the MissingURLGeneratorWarning after about half an hour or so and I was able to run the live development server.

You can compare your output with the output of the github action here: https://github.com/codeforIATI/analytics/actions/workflows/build.yml

In general, though, I just use the dev server locally, which starts fairly quickly:

```
python make_html.py --live
```

**Comment by notshi** [comment]
>In general, though, I just use the dev server locally, which starts fairly quickly:

Yes! It's definitely faster and has worked as intended. 

I was just going through the usage section sequentially so thought I had to run that first before going into the development section.
