### ISSUE TITLE
Missing data in reporting_org table

### ISSUE THREAD

**Issue by notshi** [codeforIATI/analytics#57]
**Describe the bug**
The table in the Reporting Orgs page should be populated with data but it isn't.

**To Reproduce**
1. Go to 'https://analytics.codeforiati.org/reporting_orgs.html'

**Expected behavior**
The table should be populated with data.

**Screenshots**
![Screenshot-20210818225551-1186x814](https://user-images.githubusercontent.com/1515961/129980429-78723473-ff11-4b20-9a48-4c7e171e57a9.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - Browser: Firefox 91.0 (64-bit), Google Chrome Version 92.0.4515.131 (Official Build) (64-bit)

**Comment by notshi** [comment]
Actually, I think more parts of the site is facing the same issue.

![Screenshot-20210818233602-1363x957](https://user-images.githubusercontent.com/1515961/129981012-a189eae1-be69-47a1-9bb3-b0e20486c3cd.png)
![Screenshot 2021-08-18 at 23-37-04 Code for IATI Analytics - Organisation XML Files](https://user-images.githubusercontent.com/1515961/129981100-0fd19b7a-f8f5-416d-b799-c5a683f9c99c.png)
![Screenshot 2021-08-18 at 23-36-55 Code for IATI Analytics - Duplicate Activity Identifiers](https://user-images.githubusercontent.com/1515961/129981101-27c3ea33-3875-4bd5-a254-ab5c9dac9a7b.png)

**Comment by andylolz** [comment]
Wow, yes… Good spot. I’ll look into this

**Comment by andylolz** [comment]
Aha, okay. We’re making the following request to get publishers, which is currently 504ing:
https://iatiregistry.org/api/3/action/organization_list?all_fields=true&include_extras=true&include_tags=true&include_groups=true&include_users=true&limit=50

**Comment by andylolz** [comment]
Seems like there may recently have been a CKAN update that has caused this to break.

**Comment by andylolz** [comment]
Okay great – fixed in ac168a08e34392eb6ced6d5efb37c2a93724da55.
