### ISSUE TITLE
Show the names of codes

### ISSUE THREAD

**Issue by markbrough** [codeforIATI/analytics#65]
**Is your feature request related to a problem? Please describe.**
When looking at which codelist values are used, we use the code but not the name.

**Describe the solution you'd like**
Show names as well as codes.

**Describe alternatives you've considered**
Manually looking up the name of the code on another website

**Additional context**
[Codelist Values of TransactionType codelist](https://analytics.codeforiati.org/codelist/2/transaction_transaction-type_@code.html):
<img width="581" alt="image" src="https://user-images.githubusercontent.com/688113/189169585-0b5da685-bdbe-4225-b24a-bf660d78744e.png">

[TransactionType Codelist](https://codelists.codeforiati.org/TransactionType/)
<img width="703" alt="image" src="https://user-images.githubusercontent.com/688113/189169629-d252d718-a7f3-4151-b808-2f20f37ca8c5.png">

**Comment by andylolz** [comment]
Good plan. I’ve [had a go at this on dev](https://analytics-dev.codeforiati.org/codelist/2/transaction_transaction-type_@code.html):
<img width="585" alt="Screenshot 2022-09-09 at 09 18 06" src="https://user-images.githubusercontent.com/464193/189305025-4e579fca-c78e-4cad-b0e2-d64669e0d679.png">

Should we include descriptions, too?
