### ISSUE TITLE
Percentages on the Forward Looking statistics

### ISSUE THREAD

**Issue by stevieflow** [codeforIATI/analytics#67]
For Forward Looking statistics, some publishers are rendered as 0, when in fact they would be - for example - 0.4%

Hence, for these calculations, we should print to two decimals

Related, indirectly to https://github.com/codeforIATI/analytics/issues/58

First raised on IATI Dashboard: https://github.com/IATI/IATI-Dashboard/issues/302

**Comment by andylolz** [comment]
I’ve had a go at fixing this on the forward looking page, and the summary statistics page. I’m not sure where else to look for percentages?

**Comment by andylolz** [comment]
I’ve switched off rounding completely for percentages in the CSVs. In HTML tables, we round percentages to 2 decimal places.

**Comment by andylolz** [comment]
This is on dev: https://analytics-dev.codeforiati.org/forwardlooking.html

**Comment by stevieflow** [comment]
Excellent - thanks @andylolz !

I think the only other places where this would apply would be the Averages on Comprehensiveness - which are then derived from the specific Core, Financials and Value Added averages - https://analytics-dev.codeforiati.org/comprehensiveness.html

**Comment by andylolz** [comment]
Oh, good point. Also the humanitarian reporting average: https://analytics.codeforiati.org/humanitarian.html

**Comment by andylolz** [comment]
All publishing statistics percentages are now rounded to two significant figures in HTML output:
* [Forward Looking](https://analytics.codeforiati.org/forwardlooking.html)
* [Comprehensiveness (summary)](https://analytics.codeforiati.org/comprehensiveness.html)
* [Comprehensiveness (core)](https://analytics.codeforiati.org/comprehensiveness_core.html)
* [Comprehensiveness (financials)](https://analytics.codeforiati.org/comprehensiveness_financials.html)
* [Comprehensiveness (value added)](https://analytics.codeforiati.org/comprehensiveness_valueadded.html)
* [Summary Statistics](https://analytics.codeforiati.org/summary_stats.html)
* [Humanitarian Reporting](https://analytics.codeforiati.org/humanitarian.html)

I’ve made a small amend to remove the ".0" that python adds to round floats (so e.g. 100.0 becomes 100 and 0.0 becomes 0).

Additionally, rounding has been removed from the CSV output. So none of the numbers in the CSV output are rounded.

**Comment by stevieflow** [comment]
Amazing - thanks @andylolz !
